<template>
    <div>
        <BackendPackageDetails />
        <div class="client-information px-5 py-4">
            <h2 class="client-info font-metropolis fw-bold text-20"> Client Information</h2>
            <div class="row">
                <div class="col-md-6" v-if="client_info.name">
                    <p class="text-14 font-metropolis label">
                        Full Name
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.name }}
                    </p>
                </div>
                <div class="col-md-6" v-if="client_info.email">
                    <p class="text-14 font-metropolis label">
                        Email
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.email }}
                    </p>
                </div>

                <div class="col-md-6" v-if="client_info.phone">
                    <p class="text-14 font-metropolis label">
                        Phone
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.phone }}
                    </p>
                </div>
                <div class="col-md-6" v-if="client_info.company">
                    <p class="text-14 font-metropolis label">
                        Company Name
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.company }}
                    </p>
                </div>

                <div class="col-md-6" v-if="client_info.address">
                    <p class="text-14 font-metropolis label">
                        Company Address
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.address }}
                    </p>
                </div>

                <div class="col-md-6" v-if="client_info.skype">
                    <p class="text-14 font-metropolis label">
                        Skype
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ client_info.skype }}
                    </p>
                </div>

                <div class="col-md-6">
                    <p class="text-14 font-metropolis label">
                        Quotation Generated By
                    </p>
                    <p class="fw-bold font-metropolis">
                        {{ $auth.user.name }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import moment from 'moment'
import BackendPackageDetails from './BackendPackageDetails.vue';

export default {
    data() {
        return {
            info: [],
            web_design: [],
            web_content: [],
            ecommerce: [],
            form_cost: "",
            video_cost: "",
            online_schedule: "",
            search_cap_cost: "",
            member_login_cost: "",
            analytic_cost: "",
            social_media_cost: "",
            chat_cost: "",
            blog_cost: "",
            addons: [],
            client_info: [],
        };
    },
    async mounted() {
        try {
            const info = await this.$axios.$get(`history/${this.$route.params.details}`);
            this.info = info;
            this.web_design = JSON.parse(info.web_design);
            this.web_content = JSON.parse(info.web_content);
            this.ecommerce = JSON.parse(info.ecommerce);
            this.addons = JSON.parse(info.addons);
            this.client_info = JSON.parse(info.client_info);
        }
        catch (error) {
            console.log(error);
        }
    },
    methods: {
        getAddonsPrice() {
            this.form_cost = this.addons.form_cost ? this.addons.form_cost : 0;
            this.video_cost = (this.addons.video_no) ? this.addons.video_no * 300 : 0;
            this.online_schedule = this.addons.online_schedule_cost ? this.addons.online_schedule_cost : 0;
            this.search_cap_cost = this.addons.search_cap_no ? this.addons.search_cap_no * 3000 : 0;
            this.member_login_cost = this.addons.member_login_no ? this.addons.member_login_no * 3000 : 0;
            this.analytic_cost = this.addons.analytic_no ? this.addons.analytic_no * 500 : 0;
            this.social_media_cost = this.addons.social_media_no ? this.addons.social_media_no * 300 : 0;
            this.chat_cost = this.addons.chat_setup_no ? this.addons.chat_setup_no * 500 : 0;
            this.blog_cost = this.addons.blog_setup_no ? this.addons.blog_setup_no * 5000 : 0;
            return this.form_cost + this.video_cost + this.online_schedule + this.search_cap_cost + this.member_login_cost + this.analytic_cost + this.social_media_cost + this.chat_cost + this.blog_cost;
        },
        getTotalPrice() {
            const webdesignPrice = this.web_design.price;
            const webcontPrice = this.web_content.stock_image + this.web_content.copy_writing + this.web_content.logo;
            const ecomPrice = this.ecommerce.price;
            const addonsPrice = this.getAddonsPrice();
            return webdesignPrice + webcontPrice + ecomPrice + addonsPrice;
        },
        calculateDiscount() {
            const extrdis = this.info.discount;
            return ((this.getTotalPrice() * extrdis) / 100);
        },
        dateFormat(date) {
            return moment(date).format("Do MMMM YYYY");
        },
    },
    components: { BackendPackageDetails }
}
</script>

<style lang="scss" scoped>

</style>