<template>
    <div>
        <div class="container-fluid cc-db-blue-bg py-2">
            <div class="container my-5 text-center">
                <Header />
            </div>
        </div>
        <div class="container-fluid py-5" style="background: #F7F7F7;">
            <div class="container mt-2 px-0 bg-white">
                <div class="cc-history-section history-details pb-5">
                    <BackendPackageDetails />
                </div>

                <div class="quotation-progress client-information px-5 pt-2 pb-5">
                        <h3 class="mb-3">Client Information</h3>
                        <form>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="text-14 font-metropolis label my-2">
                                        Full Name *
                                    </label>
                                    <input type="text" v-model="full_name" />
                                    <div v-if="full_name.length < 1 && full_name == '' " class="text-12 mt-2 text-warning">This field is required</div>
                                </div>

                                <div class="col-md-6 mb-3">
                                        <label class="text-14 font-metropolis label my-2">
                                            Email *
                                        </label>
                                        <input type="text" v-model="email"/>
                                        <div v-if="email.length < 1 && email == '' " class="text-12 mt-2 text-warning">This field is required</div>
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label class="text-14 font-metropolis label my-2">
                                        Phone Number
                                    </label>
                                    <input type="text" v-mask="['+1 (###) ###-####']" v-model="phone"/>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="text-14 font-metropolis label my-2">
                                        Company Name
                                    </label>
                                    <input type="text" v-model="company"/>
                                </div>

                                <div class="col-md-6 mb-3">
                                    <label class="text-14 font-metropolis label my-2">
                                        Company Address
                                    </label>
                                    <input type="text" v-model="address"/>
                                </div>

                                <div class="col-md-6 mb-3">
                                    <div class="row">
                                        <div class="col-md-4">

                                            <label class="text-14 font-metropolis label my-2">
                                                Skype
                                            </label>
                                            <input type="text" v-model="skyp"/>
                                        </div>
                                        <div class="col-md-4">

                                            <label class="text-14 font-metropolis label my-2">
                                                Linkedin
                                            </label>
                                            <input type="text" v-model="linkedin"/>
                                        </div>

                                        <div class="col-md-4">

                                            <label class="text-14 font-metropolis label my-2">
                                                Others
                                            </label>
                                            <input type="text" v-model="others"/>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6 mb-3">

                                    <label class="text-14 font-metropolis label my-2">
                                        Quotation Generated By *
                                    </label>
                                    <input type="text" v-model="quotation_by"/>

                                    <div v-if="quotation_by.length < 1 && quotation_by == '' " class="text-12 mt-2 text-warning">This field is required</div>
                                </div>
                            </div>

                            <div class="text-center">
                                <NuxtLink to="/draft" class="back-btn font-metropolis" v-if="$auth.loggedIn">Back</NuxtLink>
                                <div class="save-draft mt-5 text-center" @click="updateClient( id )">Update</div>
                            </div>
                        </form>
                    </div>

                   
            </div>
        </div>
    </div>
</template>

<script>
import BackendPackageDetails from '../../components/sections/BackendPackageDetails.vue'
import {mask} from 'vue-the-mask'

export default {
    directives: {mask},
    components: {
        BackendPackageDetails,
    },

    data() {
        return {
            'draft_panel': true,
            'edit_panel': false,
            'id': '',
            'edit': [],
            directives:{mask},
            'full_name': '',
            'email': '',
            'phone': '',
            'company': '',
            'address': '',
            'skyp': '',
            'linkedin': '',
            'others': '',
            'quotation_by': '',
        }
    },

    async mounted() {
        try {
            const histories = await this.$axios.$get(`history/${this.$route.params.details}`);
            console.log(histories);
            this.histories = histories;
            this.edit = JSON.parse(this.histories.client_info);
            this.id = this.histories.id;
            this.full_name = this.edit.name;
            this.email = this.edit.email;
            this.phone = this.edit.phone;
            this.company = this.edit.company;
            this.address = this.edit.address;
            this.skyp = this.edit.skyp;
            this.linkedin = this.edit.linkedin;
            this.others = this.edit.others;
            this.quotation_by = this.edit.quotation_by;

        } catch (error) {
            // console.log(error);
        }
    },

    methods: {
        updateClient(id){
            const update = this.$axios.$put(
                `history/${id}`, {
                        'client_info': {
                            "name":this.full_name,
                            "email": this.email,
                            "phone":  this.phone,
                            "company": this.company,
                            "address": this.address,
                            "skyp": this.skyp,
                            "linkedin": this.linkedin,
                            "others": this.others,
                            "quotation_by": this.quotation_by,
                        },
                    }
                )
                .then((res) => {
                    this.$router.push({
                        path: '/draft',
                    });
                    this.$axios.$get(
                        'history'
                    ).then((res)=>{
                        this.histories = res.data;
                    });
                    this.edit_panel = false;
                    this.draft_panel = true;
                });
        },

    }

}
</script>

<style lang="scss" scoped>
</style>